title: First stastic try
description: This is my first time trying stastic package
social_link: facebook
social_username: youssef.chlendi
github_repo: teststastic
github_username: youssefchlendi
theme_color: black
remote_theme: internet-de-france/swiss
baseurl: /teststastic
defaults:
  - scope:
      path: ''
      type: pages
    values:
      category_name: ''
  - scope:
      path: ''
      type: posts
    values:
      categories: ''
remote_theme_layouts:
  - ''
  - default
  - page
  - post
  - home
  - category_index
social_links:
  - twitter
  - instagram
  - medium
  - dribbble
theme_colors:
  - black
  - blue
  - gray
  - magenta
  - orange
  - red
  - white
  - yellow
